# ----------------------------------------------------------------------------
# Customize Options: Must Change
#
# Title:
title: שטויות ששמי כותב

# Where the page will be deployed.
# If it's https://foo.com/bar, just write "https://foo.com"
domain: "shmuelamit.github.io"
url: "https://shmuelamit.github.io"


# Set default og:image
# From Unsplash: https://unsplash.com/photos/1_CMoFsPfso


# ----------------------------------------------------------------------------
# Customize Options: Optional
#
# See: https://material.io/guidelines/style/color.html
# Use color-name-value, like pink-200 or deep-purple-100
brand_color: "light-blue-400"

# How article URLs are structured.
# See: https://jekyllrb.com/docs/permalinks/
permalink: posts/:title/

# "UA-NNNNNNNN-N"
google_analytics: ""

# Language. For example, if you write in Japanese, use "ja"
lang: "he"

# How many posts are visible on the home page without clicking "View More"
num_posts_visible_initially: 4

# Date format: See http://strftime.net/
date_format: "%b %-d, %Y"
# ----------------------------------------------------------------------------

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - mix-manifest.json
  - webpack.mix.js
  - yarn.lock
  - package.json
  - hot
  - LICENSE.txt

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-readme-index